### ISSUE TITLE
Melee Weapons Checklist

### ISSUE THREAD

**Issue by JMilamber** [BrassAmber-Mods/BrassArmory#6]
BattleAxe: (DerToaster)
- [x] can be thrown 4 blocks [thrust and velocity stuff]
- [x] entity sprite of the battleaxe spins slowly forwards as it flies through the air
- [x] sticks into a wall like an arrow
- [x] plays deeper pitched trident noise for the wide blade 'whoosh'
- [x] flies back to the player if it hits an enemy while enchanted with 'loyalty'
- [ ] battleaxe spins back to the player when returning the same way it was thrown
- [x] can smash down wooden doors if gold/wood/stone/iron
- [x] can smash down iron doors if diamond/netherite
- [x] throw has a 5-second cooldown

Spear: (DerToaster)
- [x] reach = +1
- [x] can be thrown 12 blocks [thrust and velocity stuff]
- [x] entity sprite of the spear flies forwards enemies
- [x] sticks into a wall like an arrow
- [x] uses trident throw sound
- [x] flies back to the player if it hits an enemy while enchanted with 'loyalty'
- [x] flies tip pointed at the player in a return flight
- [x] no cooldown on throw

Dagger: (DerToaster)
- [x] reach = -1
- [ ] can be thrown 8 blocks [thrust and velocity stuff]
- [ ] entity sprite of the dagger spins forwards as it flies through the air
- [x] sticks into a wall like an arrow
- [ ] plays 'weapon_toss' .ogg which needs to be trimmed to remove the delay
- [x] flies back to the player if it hits an enemy while enchanted with 'loyalty'
- [ ] dagger does not spin and instead flies tip to point at the player in a return flight
- [x] no cooldown on throw

Flail: (DerToaster)
- [ ] can be thrown 6 blocks [thrust and velocity stuff] in a straight line
- [ ] entity sprite of the flail flies forwards enemies
- [ ] bounces off walls
- [ ] no cooldown on throw
- [ ] has a line of chain texture behind it
- [ ] flail does melee damage by left-clicking as well

Halberd:
- [x] reach= +2
- [ ] right click to activate guard [resistance]
- [ ] resistance 1 for wood/gold/stone
- [ ] resistance 2 for iron/diamond
- [ ] resistance 3 for netherite
- [ ] guard only works if halberd remains in hand
- [ ] swapping hands end the effect
- [ ] effect lasts 10 seconds with a 20 second cooldown after it ends
- [ ] if hands are swapped, remaining time is added to cooldown [max 30]
- [ ] consumes 10 durability

Mace: (Jodi - 1.18)
- [x] charge by holding right-click until max [3 seconds] 
- [x] release to perform AoE smash
- [x] damage is based on the crit damage of the tier of the weapon
- [x] 30-second cooldown upon use
- [x] does not break blocks
- [x] deals knockback to push away enemies [4 blocks]
- [x] consumes 10 durability

**Comment by jodlodi** [comment]
Fully implemented
