### ISSUE TITLE
Ranged Weapons Checklist

### ISSUE THREAD

**Issue by JMilamber** [BrassAmber-Mods/BrassArmory#7]
Bombs: (@jodlodi )
- [x] right-click to light fuse
- [x] right-click again to throw
- [x] animation begins when the fuse is lit
- [x] animation is 3 seconds long
- [x] explosion is a 2x2 sphere [2x2 center with a 2x2 on each side]
- [x] bomb slides along the ground [if it can be animated to roll as it slides that'd be awesome]
- [x] sticky bomb sticks to walls
- [x] bouncy bomb bounces off walls, accelerating on each bounce
- [x] bomb can blow up in hand if not thrown
- [x] does not collide with mobs, only solid surfaces
- [x] bomb will not break tiles underwater

Boomerang: @jodlodi 
- [x] right-click and hold to charge (The longer the charge, the further the throw)
- [x] release to throw [hold time effects distance like a bow with a min and max]
- [ ] boomerang falls to the ground with a charge less than 0.5 seconds
- [x] spins as it flies and returns to the player
- [x] hits enemies and continues flight through
- [x] can fly through waterfalls and lava falls [takes 1 durability for every tick in lava]
- [x] can miss the player and stick into the ground if they move when it's close
- [x] default= boomerang returns to slot unless the slot is taken, then it goes to the next slot
- [x] loyalty= always returns to slot once it stops moving even if player moves out of the way
- [x] falls to the ground if inventory is full
- [x] will go into off-hand if the slot is only one open
- [x] can be thrown from both hands [not 2 at once]
- [ ] block interaction [To Be Determined]
- [x] melee damage does 3 durability
- [x] throw does 1 durability
- [ ] can be thrown underwater if enchanted with Aqua Affinity
- [x] QuickCharge Enchant [default charge time= 2 seconds, QC1= 1 second, QC2= half second]
- [ ] Flaming Boomerang sets off TNT

Musket: (@jodlodi):
(check the video I don't have a list for this yet)

Blunderbuss (@jodlodi):
(check the video I don't have a list for this yet)

**Comment by jodlodi** [comment]
Fully implemented
